import { Activity, Clock3, Plus, RotateCw, Save, ShieldCheck } from 'lucide-react'
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { createMarket, createMission, getAdminMissions, getAuditLogs, updateMarket, updateMission, type AdminMission, type AuditLog, type MissionInput } from '../api/admin'
import { PageHeader } from '../components/PageHeader'
import type { MissionStatus } from '../types/mission'

type AdminData = { missions: AdminMission[]; auditLogs: AuditLog[] }
type State = { status: 'loading' } | { status: 'success'; data: AdminData } | { status: 'error'; message: string }
type Notice = { kind: 'success' | 'error'; message: string } | null
const setupStatuses: MissionStatus[] = ['DRAFT', 'REGISTRATION', 'LOCKED']
const configurationStatuses: MissionStatus[] = ['DRAFT', 'REGISTRATION', 'LOCKED']

export function AdminPage() {
  const [state, setState] = useState<State>({ status: 'loading' })
  const [notice, setNotice] = useState<Notice>(null)
  const load = useCallback(async (signal?: AbortSignal) => {
    try {
      const [missions, auditLogs] = await Promise.all([getAdminMissions(signal), getAuditLogs(signal)])
      setState({ status: 'success', data: { missions: missions.data, auditLogs: auditLogs.data } })
    } catch (error: unknown) {
      if (error instanceof DOMException && error.name === 'AbortError') return
      setState({ status: 'error', message: error instanceof Error ? error.message : 'Mission controls could not be loaded.' })
    }
  }, [])
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort() } }, [load])
  async function mutate(action: () => Promise<unknown>, message: string) {
    setNotice(null)
    try { await action(); await load(); setNotice({ kind: 'success', message }) }
    catch (error: unknown) { setNotice({ kind: 'error', message: error instanceof Error ? error.message : 'Administrative action failed.' }) }
  }

  return <div><PageHeader title="Mission control" />
    <div className="mt-8 grid gap-px bg-line sm:grid-cols-3"><StatusMetric icon={<ShieldCheck />} label="Access" value="Admin verified" /><StatusMetric icon={<Activity />} label="Lifecycle" value="Automation online" /><StatusMetric icon={<Clock3 />} label="Cycle" value="Continuous" /></div>
    {notice && <p className={`mt-6 border p-4 text-sm ${notice.kind === 'error' ? 'border-danger/40 bg-danger/5 text-danger' : 'border-primary/30 bg-primary/5 text-ink'}`} role={notice.kind === 'error' ? 'alert' : 'status'}>{notice.message}</p>}
    <div className="mt-10"><MissionForm onSubmit={(input) => mutate(() => createMission(input), 'Mission created and audit recorded.')} /></div>
    <section className="mt-10" aria-labelledby="existing-title"><div className="mb-4 flex items-center justify-between gap-4"><h2 id="existing-title" className="text-sm font-semibold uppercase tracking-wider text-ink">Existing missions</h2><button type="button" onClick={() => void load()} className="focus-ring inline-flex min-h-10 items-center gap-2 px-2 text-sm text-muted hover:text-ink"><RotateCw className="size-4" aria-hidden="true" /> Refresh</button></div>
      {state.status === 'loading' ? <div className="space-y-3" aria-busy="true">{[0, 1].map((item) => <div key={item} className="h-24 animate-pulse border border-line bg-surface" />)}</div> : state.status === 'error' ? <div className="border border-danger/40 bg-danger/5 p-5" role="alert"><p className="text-danger">{state.message}</p><button type="button" onClick={() => void load()} className="focus-ring mt-4 min-h-10 border border-line px-4 text-sm text-ink">Retry</button></div> : state.data.missions.length === 0 ? <p className="border border-dashed border-line p-6 text-sm text-muted">No missions yet. Create the first scheduled operation above.</p> : <div className="space-y-5">{state.data.missions.map((mission) => <MissionEditor key={mission.id} mission={mission} onMutate={mutate} />)}</div>}
    </section>
    <section className="mt-12" aria-labelledby="audit-title"><div className="mb-4"><h2 id="audit-title" className="text-xl font-semibold text-ink">Audit log</h2></div>
      {state.status === 'loading' ? <div className="h-48 animate-pulse border border-line bg-surface" aria-busy="true" /> : state.status === 'error' ? <p className="border border-line p-5 text-sm text-muted">Audit history is unavailable until mission control reconnects.</p> : state.data.auditLogs.length === 0 ? <p className="border border-dashed border-line p-6 text-sm text-muted">No administrative or lifecycle actions recorded yet.</p> : <AuditTable logs={state.data.auditLogs} />}
    </section>
  </div>
}

function MissionForm({ onSubmit }: { onSubmit: (input: MissionInput) => Promise<void> }) {
  const defaults = defaultForm(); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [balance, setBalance] = useState('10000'); const [status, setStatus] = useState<MissionStatus>('REGISTRATION'); const [startsAt, setStartsAt] = useState(defaults.startsAt); const [endsAt, setEndsAt] = useState(defaults.endsAt); const [allowDynamicMarkets, setAllowDynamicMarkets] = useState(false); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await onSubmit({ name, description: description || null, startingBalance: Number(balance), status, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), allowDynamicMarkets }); setName(''); setDescription('') } finally { setBusy(false) } }
  return <form onSubmit={submit} className="border border-line bg-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Plus className="size-5 text-primary" aria-hidden="true" /><h2 className="text-lg font-semibold text-ink">Create mission</h2></div><p className="mt-2 text-sm text-muted">Automation owns ACTIVE, BLACKOUT, SETTLING, and FINALIZED after scheduling.</p><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Name"><input required minLength={3} autoComplete="off" value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></Field><Field label="Starting balance"><input required type="text" inputMode="decimal" autoComplete="off" value={balance} onChange={(event) => setBalance(event.target.value)} className={inputClass} /></Field><Field label="Starts at"><input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} className={inputClass} /></Field><Field label="Ends at"><input required type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} className={inputClass} /></Field><Field label="Initial status"><StatusSelect value={status} onChange={setStatus} options={setupStatuses} /></Field><Field label="Brief"><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} className={inputClass} /></Field></div><label className="mt-5 flex cursor-pointer items-start gap-3 border border-line bg-canvas p-4 text-sm text-ink"><input type="checkbox" checked={allowDynamicMarkets} onChange={(event) => setAllowDynamicMarkets(event.target.checked)} className="focus-ring mt-0.5 size-4 shrink-0 accent-primary" /><span><strong className="block">Open Arena</strong><span className="mt-1 block text-xs leading-5 text-muted">Let deployed participants admit new Jupiter-routable tokens after liquidity and two-way route checks. This setting locks when trading begins.</span></span></label><button disabled={busy} aria-busy={busy} className="focus-ring mt-6 min-h-11 bg-primary px-5 text-sm font-semibold text-primary-ink disabled:cursor-wait disabled:opacity-50">{busy ? 'Creating…' : 'Create mission'}</button></form>
}

function MissionEditor({ mission, onMutate }: { mission: AdminMission; onMutate: (action: () => Promise<unknown>, message: string) => Promise<void> }) {
  const [name, setName] = useState(mission.name); const [description, setDescription] = useState(mission.description ?? ''); const [balance, setBalance] = useState(mission.startingBalance); const [status, setStatus] = useState<MissionStatus>(mission.status); const [startsAt, setStartsAt] = useState(toLocal(mission.startsAt)); const [endsAt, setEndsAt] = useState(toLocal(mission.endsAt)); const [allowDynamicMarkets, setAllowDynamicMarkets] = useState(mission.allowDynamicMarkets); const [symbol, setSymbol] = useState(''); const [mint, setMint] = useState(''); const [decimals, setDecimals] = useState('6'); const [busy, setBusy] = useState(false)
  const configurationOpen = configurationStatuses.includes(mission.status)
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { await onMutate(() => updateMission(mission.id, { name, description: description || null, startingBalance: Number(balance), status, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), allowDynamicMarkets }), `${mission.name} updated and audited.`) } finally { setBusy(false) } }
  async function add(event: FormEvent) { event.preventDefault(); await onMutate(() => createMarket(mission.id, { symbol, mintAddress: mint, decimals: Number(decimals), enabled: true }), `${symbol.toUpperCase()} added and audited.`); setSymbol(''); setMint(''); setDecimals('6') }
  return <details className="border border-line bg-surface"><summary className="focus-ring flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 px-5"><span><strong className="text-ink">{mission.name}</strong><span className="ml-3 font-mono text-xs text-muted">{mission.status} · {mission.operatorCount} participants</span></span><span className="font-mono text-xs text-muted">{mission.resultCount} results</span></summary><div className="border-t border-line p-5">
    {mission.lifecycleError && <p className="mb-5 border border-danger/40 bg-danger/5 p-4 text-sm text-danger" role="alert">Settlement retry pending: {mission.lifecycleError}</p>}
    {mission.settledAt && <p className="mb-5 font-mono text-xs uppercase tracking-wider text-primary">Settled {formatTimestamp(mission.settledAt)}</p>}
    <form onSubmit={save}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Name"><input required value={name} onChange={(event) => setName(event.target.value)} className={inputClass} /></Field><Field label="Starting balance"><input required disabled={!configurationOpen} type="text" inputMode="decimal" value={balance} onChange={(event) => setBalance(event.target.value)} className={inputClass} /></Field><Field label="Status"><StatusSelect value={status} onChange={setStatus} options={statusOptions(mission.status)} /></Field><Field label="Starts at"><input required disabled={!configurationOpen} type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} className={inputClass} /></Field><Field label="Ends at"><input required disabled={!configurationOpen} type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} className={inputClass} /></Field><Field label="Brief"><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={2} className={inputClass} /></Field></div><label className="mt-4 flex min-h-11 items-center gap-3 text-sm text-ink"><input type="checkbox" disabled={!configurationOpen} checked={allowDynamicMarkets} onChange={(event) => setAllowDynamicMarkets(event.target.checked)} className="focus-ring size-4 accent-primary" /> Open Arena: participants can admit eligible Jupiter tokens</label><button disabled={busy} aria-busy={busy} className="focus-ring mt-5 inline-flex min-h-11 items-center gap-2 border border-primary px-4 text-sm font-semibold text-primary disabled:cursor-wait disabled:opacity-50"><Save className="size-4" aria-hidden="true" /> {busy ? 'Saving…' : 'Save mission'}</button></form>
    <div className="mt-8 border-t border-line pt-6"><div><h3 className="text-sm font-semibold uppercase tracking-wider text-ink">Approved markets</h3>{!configurationOpen && <p className="mt-2 text-sm text-muted">Market configuration locked when trading began.</p>}</div><div className="mt-4 divide-y divide-line border-y border-line">{mission.markets.length === 0 ? <p className="py-5 text-sm text-muted">No markets configured.</p> : mission.markets.map((market) => <div key={market.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><span><strong className="text-ink">{market.symbol}</strong><span className="ml-3 font-mono text-xs text-muted">{market.mintAddress.slice(0, 6)}...{market.mintAddress.slice(-6)} · {market.decimals} decimals{market.settlementPrice ? ` · final $${market.settlementPrice}` : ''}</span></span><label className="flex min-h-10 cursor-pointer items-center gap-2 text-sm text-muted"><input type="checkbox" disabled={!configurationOpen} checked={market.enabled} onChange={(event) => void onMutate(() => updateMarket(mission.id, market.id, { enabled: event.target.checked }), `${market.symbol} ${event.target.checked ? 'enabled' : 'disabled'} and audited.`)} className="focus-ring size-4 accent-primary" /> Enabled</label></div>)}</div>
      {configurationOpen && <form onSubmit={add} className="mt-5 grid gap-4 sm:grid-cols-[8rem_1fr_8rem_auto]"><Field label="Symbol"><input required autoComplete="off" value={symbol} onChange={(event) => setSymbol(event.target.value)} className={inputClass} /></Field><Field label="Mint address"><input required minLength={32} autoComplete="off" value={mint} onChange={(event) => setMint(event.target.value)} className={inputClass} /></Field><Field label="Decimals"><input required type="number" min="0" max="18" value={decimals} onChange={(event) => setDecimals(event.target.value)} className={inputClass} /></Field><button className="focus-ring min-h-11 self-end border border-line px-4 text-sm text-ink hover:border-primary">Add market</button></form>}
    </div></div></details>
}

function AuditTable({ logs }: { logs: AuditLog[] }) { return <div className="overflow-x-auto border border-line bg-surface"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-line font-mono text-xs uppercase tracking-wider text-muted"><tr><th className="px-4 py-3 font-normal">Time</th><th className="px-4 py-3 font-normal">Actor</th><th className="px-4 py-3 font-normal">Action</th><th className="px-4 py-3 font-normal">Target</th></tr></thead><tbody className="divide-y divide-line">{logs.map((log) => <tr key={log.id}><td className="px-4 py-3 font-mono text-xs text-muted">{formatTimestamp(log.createdAt)}</td><td className="px-4 py-3 font-mono text-xs text-ink">{log.actorType === 'SYSTEM' ? 'SYSTEM' : truncate(log.actorWallet)}</td><td className="px-4 py-3 text-ink">{log.action.replaceAll('_', ' ')}</td><td className="px-4 py-3 font-mono text-xs text-muted">{log.entityType} · {log.entityId.slice(-8)}</td></tr>)}</tbody></table></div> }
function StatusMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="bg-surface p-4"><p className="flex items-center gap-2 text-xs uppercase tracking-wider text-muted"><span className="[&>svg]:size-4 [&>svg]:text-primary">{icon}</span>{label}</p><p className="mt-2 font-mono text-sm text-ink">{value}</p></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-ink"><span className="mb-2 block text-xs uppercase tracking-wider text-muted">{label}</span>{children}</label> }
function StatusSelect({ value, onChange, options }: { value: MissionStatus; onChange: (value: MissionStatus) => void; options: MissionStatus[] }) { return <select value={value} onChange={(event) => onChange(event.target.value as MissionStatus)} className={inputClass}>{options.map((item) => <option key={item} value={item}>{item}</option>)}</select> }
function statusOptions(current: MissionStatus): MissionStatus[] { if (current === 'FINALIZED') return ['FINALIZED', 'CLOSED']; if (current === 'CLOSED' || current === 'CANCELLED') return [current]; if (configurationStatuses.includes(current)) return [...setupStatuses, 'CANCELLED']; return [current, 'CANCELLED'] }
const inputClass = 'min-h-11 w-full border border-line bg-canvas px-3 py-2 text-ink focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/40 disabled:cursor-not-allowed disabled:text-muted'
function truncate(value: string | null) { return value ? `${value.slice(0, 4)}...${value.slice(-4)}` : 'unknown' }
function formatTimestamp(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function toLocal(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16) }
function defaultForm() { const start = new Date(Date.now() + 3_600_000); const end = new Date(Date.now() + 25 * 3_600_000); return { startsAt: toLocal(start.toISOString()), endsAt: toLocal(end.toISOString()) } }
