import { Award, Crosshair, Medal, RotateCw } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { getProfile, type ProfileSummary } from '../api/profile'
import { AuthenticationRequired } from '../components/AuthenticationRequired'
import { PageHeader } from '../components/PageHeader'
import { useAuth } from '../providers/auth-context'
import { formatCurrency, formatPercent } from '../lib/format'

type State = { status: 'loading' } | { status: 'success'; data: ProfileSummary } | { status: 'error'; message: string }

export function ProfilePage() {
  const auth = useAuth()
  const [state, setState] = useState<State>({ status: 'loading' })
  const load = useCallback(async (signal?: AbortSignal) => { setState({ status: 'loading' }); try { const { data } = await getProfile(signal); setState({ status: 'success', data }) } catch (error: unknown) { if (error instanceof DOMException && error.name === 'AbortError') return; setState({ status: 'error', message: error instanceof Error ? error.message : 'Profile could not be loaded.' }) } }, [])
  useEffect(() => { if (auth.status !== 'authenticated') return; const controller = new AbortController(); const timer = window.setTimeout(() => void load(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort() } }, [auth.status, auth.user?.userId, load])
  if (auth.status === 'loading' || auth.status === 'signing') return <div aria-busy="true"><PageHeader eyebrow="Operator" title="Profile" description="Verifying operator session…" /><div className="mt-10 h-80 animate-pulse border border-line bg-surface" /></div>
  if (auth.status !== 'authenticated') return <AuthenticationRequired title="Authenticate to view your dossier" />
  if (state.status === 'loading') return <div aria-busy="true"><PageHeader eyebrow="Operator" title="Profile" description="Loading operator record…" /><div className="mt-10 h-80 animate-pulse border border-line bg-surface" /></div>
  if (state.status === 'error') return <div><PageHeader eyebrow="Operator" title="Profile unavailable" description={state.message} /><button type="button" onClick={() => void load()} className="focus-ring mt-8 inline-flex min-h-11 items-center gap-2 border border-line px-4 text-sm text-ink"><RotateCw className="size-4" /> Retry</button></div>
  const profile = state.data
  return <div><PageHeader eyebrow="Operator dossier" title={profile.username} description={profile.wallet ? `Linked wallet: ${profile.wallet.slice(0, 4)}...${profile.wallet.slice(-4)}` : 'Authenticated Falcon operator'} /><dl className="mt-10 grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-5"><Metric icon={<Crosshair />} label="Missions entered" value={String(profile.missionsEntered)} /><Metric icon={<Award />} label="Wins" value={String(profile.wins)} /><Metric icon={<Medal />} label="Top-three finishes" value={String(profile.topThreeFinishes)} /><Metric label="Average return" value={formatPercent(profile.averageReturn)} /><Metric label="Best result" value={profile.bestResult ? `${profile.bestResult.rank ? `#${profile.bestResult.rank} · ` : ''}${formatPercent(profile.bestResult.returnPercent)}` : '—'} /></dl><section className="mt-8 border border-line bg-surface" aria-labelledby="records-title"><div className="border-b border-line px-5 py-4"><h2 id="records-title" className="text-sm font-semibold uppercase tracking-wider text-ink">Mission results</h2></div>{profile.results.length === 0 ? <p className="p-8 text-center text-sm text-muted">Deploy into a mission to establish an operator record.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-line font-mono text-xs uppercase tracking-wider text-muted"><tr><th className="px-5 py-3 font-normal">Mission</th><th className="px-5 py-3 font-normal">Rank</th><th className="px-5 py-3 font-normal">Final equity</th><th className="px-5 py-3 font-normal">Return</th></tr></thead><tbody className="divide-y divide-line">{profile.results.map((result) => <tr key={result.missionId}><td className="px-5 py-4 font-medium text-ink">{result.missionName}</td><td className="px-5 py-4 font-mono text-muted">{result.rank ? `#${result.rank}` : '—'}</td><td className="px-5 py-4 font-mono text-ink">{formatCurrency(result.equity)}</td><td className={`px-5 py-4 font-mono ${Number(result.returnPercent) >= 0 ? 'text-primary' : 'text-danger'}`}>{formatPercent(result.returnPercent)}</td></tr>)}</tbody></table></div>}</section></div>
}

function Metric({ icon, label, value }: { icon?: React.ReactNode; label: string; value: string }) { return <div className="bg-surface p-5"><dt className="flex items-center gap-2 text-xs uppercase tracking-wider text-muted">{icon && <span className="[&>svg]:size-4">{icon}</span>}{label}</dt><dd className="mt-3 font-mono text-2xl text-ink">{value}</dd></div> }
